plugin:
    name: 'dmitrybykov.swiper::lang.plugin.name'
    description: 'Most Modern Mobile Touch Slider'
    author: CRYDEsigN
    icon: oc-icon-sliders
    homepage: ''
navigation:
    swiper:
        label: 'dmitrybykov.swiper::lang.plugin.name'
        url: dmitrybykov/swiper/news
        icon: icon-sliders
        iconSvg: plugins/dmitrybykov/swiper/assets/images/logo.png
        order: 700
