list: $/dmitrybykov/swiper/models/slider/columns.yaml
modelClass: dmitrybykov\Swiper\Models\Slider
title: Slider
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'dmitrybykov/swiper/slider/update/:id'
